colorlist = ("Blue", "Yellow", "Orange", "Red", "Green")
print("I have " + str(len(colorlist)) + " colors")
print(colorlist[0])
print(colorlist[1])
print(colorlist[2])
print(colorlist[3])
print(colorlist[4])